### ISSUE TITLE
Send Mails via Transactional Email Service

### ISSUE THREAD

**Issue by alanderex** [PioneersHub/pytanis#25]
## Describe your use-case
Helpdesk has been unreliable and hard to set up. Sending ist throttled. Helpdesk is not a good option for sending emails.

## Describe the solution you would like to see for your use-case
Implement a transactional Email service like Mailgun, Mailchimp or others as alternative.

**Comment by FlorianWilhelm** [comment]
This was fixed in PR #37 and PR #38 by @FinkeNils
